language:
  - node_js
node_js:
  - 9.5.0
before_install:
  - npm install -g lerna
cache:
  npm: true
services:
  - docker
install:
  - npm install
  - lerna bootstrap
  - cd packages/forgae-cli
  - npm link
  - cd ../..
script:
  - npm test
